
package com.azuki3.study.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Hello", targetNamespace = "http://ws.study.azuki3.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Hello {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://ws.study.azuki3.com/", className = "com.azuki3.study.ws.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://ws.study.azuki3.com/", className = "com.azuki3.study.ws.SayHelloResponse")
    public String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello2", targetNamespace = "http://ws.study.azuki3.com/", className = "com.azuki3.study.ws.SayHello2")
    @ResponseWrapper(localName = "sayHello2Response", targetNamespace = "http://ws.study.azuki3.com/", className = "com.azuki3.study.ws.SayHello2Response")
    public String sayHello2(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws HelloException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello3", targetNamespace = "http://ws.study.azuki3.com/", className = "com.azuki3.study.ws.SayHello3")
    @ResponseWrapper(localName = "sayHello3Response", targetNamespace = "http://ws.study.azuki3.com/", className = "com.azuki3.study.ws.SayHello3Response")
    public String sayHello3(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws HelloException_Exception
    ;

}
