
package com.azuki3.study.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "HelloException", targetNamespace = "http://ws.study.azuki3.com/")
public class HelloException_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private HelloException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public HelloException_Exception(String message, HelloException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public HelloException_Exception(String message, HelloException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.azuki3.study.ws.HelloException
     */
    public HelloException getFaultInfo() {
        return faultInfo;
    }

}
