//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.1
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloServiceClientApplication.HelloServiceReference {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.study.azuki3.com/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.study.azuki3.com/")]
    public partial class HelloException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.study.azuki3.com/", ConfigurationName="HelloServiceReference.Hello")]
    public interface Hello {
        
        // CODEGEN: パラメーター 'return' には、パラメーター モードを使用して取得できない追加のスキーマ情報が必要です。具体的な属性は 'System.Xml.Serialization.XmlElementAttribute' です。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        HelloServiceClientApplication.HelloServiceReference.sayHelloResponse sayHello(HelloServiceClientApplication.HelloServiceReference.sayHelloRequest request);
        
        // CODEGEN: パラメーター 'return' には、パラメーター モードを使用して取得できない追加のスキーマ情報が必要です。具体的な属性は 'System.Xml.Serialization.XmlElementAttribute' です。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(HelloServiceClientApplication.HelloServiceReference.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        HelloServiceClientApplication.HelloServiceReference.sayHello2Response sayHello2(HelloServiceClientApplication.HelloServiceReference.sayHello2Request request);
        
        // CODEGEN: パラメーター 'return' には、パラメーター モードを使用して取得できない追加のスキーマ情報が必要です。具体的な属性は 'System.Xml.Serialization.XmlElementAttribute' です。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(HelloServiceClientApplication.HelloServiceReference.HelloException), Action="", Name="HelloException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        HelloServiceClientApplication.HelloServiceReference.sayHello3Response sayHello3(HelloServiceClientApplication.HelloServiceReference.sayHello3Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sayHello", WrapperNamespace="http://ws.study.azuki3.com/", IsWrapped=true)]
    public partial class sayHelloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.study.azuki3.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public sayHelloRequest() {
        }
        
        public sayHelloRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sayHelloResponse", WrapperNamespace="http://ws.study.azuki3.com/", IsWrapped=true)]
    public partial class sayHelloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.study.azuki3.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public sayHelloResponse() {
        }
        
        public sayHelloResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sayHello2", WrapperNamespace="http://ws.study.azuki3.com/", IsWrapped=true)]
    public partial class sayHello2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.study.azuki3.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public sayHello2Request() {
        }
        
        public sayHello2Request(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sayHello2Response", WrapperNamespace="http://ws.study.azuki3.com/", IsWrapped=true)]
    public partial class sayHello2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.study.azuki3.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public sayHello2Response() {
        }
        
        public sayHello2Response(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sayHello3", WrapperNamespace="http://ws.study.azuki3.com/", IsWrapped=true)]
    public partial class sayHello3Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.study.azuki3.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public sayHello3Request() {
        }
        
        public sayHello3Request(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sayHello3Response", WrapperNamespace="http://ws.study.azuki3.com/", IsWrapped=true)]
    public partial class sayHello3Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.study.azuki3.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public sayHello3Response() {
        }
        
        public sayHello3Response(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HelloChannel : HelloServiceClientApplication.HelloServiceReference.Hello, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloClient : System.ServiceModel.ClientBase<HelloServiceClientApplication.HelloServiceReference.Hello>, HelloServiceClientApplication.HelloServiceReference.Hello {
        
        public HelloClient() {
        }
        
        public HelloClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HelloClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HelloServiceClientApplication.HelloServiceReference.sayHelloResponse HelloServiceClientApplication.HelloServiceReference.Hello.sayHello(HelloServiceClientApplication.HelloServiceReference.sayHelloRequest request) {
            return base.Channel.sayHello(request);
        }
        
        public string sayHello(string arg0) {
            HelloServiceClientApplication.HelloServiceReference.sayHelloRequest inValue = new HelloServiceClientApplication.HelloServiceReference.sayHelloRequest();
            inValue.arg0 = arg0;
            HelloServiceClientApplication.HelloServiceReference.sayHelloResponse retVal = ((HelloServiceClientApplication.HelloServiceReference.Hello)(this)).sayHello(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HelloServiceClientApplication.HelloServiceReference.sayHello2Response HelloServiceClientApplication.HelloServiceReference.Hello.sayHello2(HelloServiceClientApplication.HelloServiceReference.sayHello2Request request) {
            return base.Channel.sayHello2(request);
        }
        
        public string sayHello2(string arg0) {
            HelloServiceClientApplication.HelloServiceReference.sayHello2Request inValue = new HelloServiceClientApplication.HelloServiceReference.sayHello2Request();
            inValue.arg0 = arg0;
            HelloServiceClientApplication.HelloServiceReference.sayHello2Response retVal = ((HelloServiceClientApplication.HelloServiceReference.Hello)(this)).sayHello2(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HelloServiceClientApplication.HelloServiceReference.sayHello3Response HelloServiceClientApplication.HelloServiceReference.Hello.sayHello3(HelloServiceClientApplication.HelloServiceReference.sayHello3Request request) {
            return base.Channel.sayHello3(request);
        }
        
        public string sayHello3(string arg0) {
            HelloServiceClientApplication.HelloServiceReference.sayHello3Request inValue = new HelloServiceClientApplication.HelloServiceReference.sayHello3Request();
            inValue.arg0 = arg0;
            HelloServiceClientApplication.HelloServiceReference.sayHello3Response retVal = ((HelloServiceClientApplication.HelloServiceReference.Hello)(this)).sayHello3(inValue);
            return retVal.@return;
        }
    }
}
